name = "Replication_of_Sieg_Yoon_2017"
uuid = "4b526a2b-8d01-420f-8dd4-63e83316e477"
authors = ["Victor Ho <victor.ho@sciencespo.fr>"]
version = "0.1.0"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
